### ISSUE TITLE
tried installing: torch.utis.ffi is depreciated

### ISSUE THREAD

**Issue by gereka** [iamalbert/pytorch-wordemb#4]
```
$ pip install --user torchwordemb
Collecting torchwordemb
  Using cached https://files.pythonhosted.org/packages/ab/26/a811077fa6971b2d010cb7c10bbed18cb5182219706b71d7d151f9e6a838/torchwordemb-0.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-avn748hy/torchwordemb/setup.py", line 17, in <module>
        import build
      File "/tmp/pip-install-avn748hy/torchwordemb/build.py", line 2, in <module>
        from torch.utils.ffi import create_extension
      File "/opt/python/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
        raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
    ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-avn748hy/torchwordemb/
```
I have PyTorch 1.0. When I install PyTorch 0.4.0 on a virtual environment and then install torchwordemb on top of that, I don't get this error.

**Comment by xiaoleihuang** [comment]
I have the same error, do we have any alternatives? @gereka

**Comment by gereka** [comment]
I couldn't find any that were satisfactory and gave up. For extant code that uses torchwordemb the solution is to use a virtual environment or refactor the code to use something else. For newly written code I think I'd use torchtext, gensim or maybe spacy.
